/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./LendProtocol.types";
import * as _1 from "./LendProtocol.client";
import * as _2 from "./LendProtocol.message-composer";
import * as _3 from "./LendProtocol.message-builder";
export namespace contracts {
  export const LendProtocol = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}